version: '3.4'
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: gateway
        PORT: 3000
    image: ${REPO:-turbine}/gateway:${TAG:-latest}
    depends_on:
      - zookeeper
      - database
    ports:
      - "3000:3000"
    environment:
      ZK_HOST: zookeeper:2181
      ZK_ROOT_PATH: '/services'
      SERVICE_NAME: gateway
      DATABASE_URL: postgresql://postgres:microservices@database:5432/turbine
  collect-svc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: collect-svc
        PORT: 3001
    image: ${REPO:-turbine}/collect-svc:${TAG:-latest}
    depends_on:
      - zookeeper
      - database
    environment:
      identity: producation
      ZK_HOST: zookeeper:2181
      ZK_ROOT_PATH: '/services'
      SERVICE_NAME: 'collect'
      DATABASE_URL: postgresql://postgres:microservices@database:5432/turbine
  message-svc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: message-svc
        PORT: 3002
    image: ${REPO:-turbine}/message-svc:${TAG:-latest}
    depends_on:
      - zookeeper
      - database
    environment:
      identity: producation
      GRPC_PORT: 3003
      ZK_HOST: zookeeper:2181
      ZK_ROOT_PATH: '/services'
      SERVICE_NAME: 'message'
      DATABASE_URL: postgresql://postgres:microservices@database:5432/turbine
  database:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: microservices
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper:
    image: zookeeper:3.7.0
    restart: always
    hostname: zookeeper
    ports:
      - 2182:2181